### ISSUE TITLE
Commitar os sources.

### ISSUE THREAD

**Issue by PauloLuan** [vinicius-hso/api-fatec-2s-gswatcher#1]
Caso seja possível, gostaria que vocês trabalhassem aqui no Github, organizando as frentes de trabalho, criando issues, usando a aba 'Projects' também.

Seria interessante porque eu conseguiria acompanhar melhor.

**Comment by mariana299** [comment]
Criamos a branch "development" que é agora o nosso ambiente de desenvolvimento, onde compartilhamos o código em andamento. Nesta branch a pasta "Nodejs" refere-se ao backend da aplicação e a pasta "gswatcher" ao front-end.  

Estamos utilizando as "Issues" para reportar problemas e/ou pontos  melhorias do código.  

E estamos utilizando "Projects" do Github  para informar andamento das atividades do backlog. 

Por favor, nos informe caso não esteja de acordo com sua expectativa, ou se há algum ponto de melhoria quanto a essa organização.
