### ISSUE TITLE
Botão upload

### ISSUE THREAD

**Issue by mariana299** [vinicius-hso/api-fatec-2s-gswatcher#4]
Alguém poderia testar o botão Upload e Save Data?
Para confirmar que funciona em outros lugares além da minha máquina.

**Comment by vinicius-hso** [comment]
Para mim não funcionou. É necessário que mais pessoas testem.

__IMPORTANTE__: 

1. É necessário instalar as novas dependências antes de realizar o teste utilizando `npm install`
2. Não funciona com Nodemon, então ao invés de usar `npm start` é necessário usar `node app.js`

**Comment by mariana299** [comment]
SOLUÇÃO: funciona com o comando "node app.js" 

Não funciona o nodemon, pois quando utiliza essa biblioteca é gerado um problema de escopo no código. 
Eu declarei uma variável com escopo global em uma rota, a qual não é identificada para outra rota (apenas quando o módulo nodemon está ativo isto ocorre)

Já que está funcionando com "node app.js" sem utilizar o nodemon, sugiro manter o código como está, ja que temos tempo limitado para executar as outras atividades.

PONTO DE ATENÇAO:
Verificar se funcionará quando fizer o deploy da aplicação.
