### ISSUE TITLE
Botão Save Data

### ISSUE THREAD

**Issue by mariana299** [vinicius-hso/api-fatec-2s-gswatcher#5]
Além do botão upload, tive que criar o botão "SAVE DATA", que é responsável por salvar os dados no banco, mas ele só funciona depois que estiver feito o upload do arquivo *.json

Então o ideal seria melhorar o front para esse botão aparecesse somente depois de fazer o upload do arquivo.

E melhorar melhorar o botão esteticamente.

**Comment by vinicius-hso** [comment]
# Melhorias

* 1. Exibir o botão __Save Data__ depois do upload do arquivo
* 2. Exibir mensagem de confirmação depois de realizar o upload

**Comment by mariana299** [comment]
Concluído!
